cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

network.host: _non_loopback:ipv4_

path:
  data: /data/data
  logs: /data/log
  plugins: /elasticsearch/plugins
  work: /data/work

bootstrap.mlockall: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: true

discovery.zen.ping.multicast.enabled: ${MULTICAST}
